### ISSUE TITLE
Not work with ios 10.1

### ISSUE THREAD

**Issue by topperblues** [VideoSpike/nativescript-screen-orientation#4]
Hi, after update to nativescript 2.3 xcode 8 and ios 10.1, setCurrentOrientation has no effect.

**Comment by NickArgyle** [comment]
I get errors with iOS 10:

JavaScript error:
file:///app/tns_modules/nativescript-screen-orientation/screen-orientation.js:103:47: JS ERROR TypeError: UIApplication.sharedApplication is not a function.

**Comment by jonathan-casarrubias** [comment]
yup same here

**Comment by Daxito** [comment]
+1

**Comment by irman** [comment]
I'm forking this plugin and will push a new npm package under my namespace.

**Comment by irman** [comment]
Published a new plugin on npm that fixed the issue mentioned by @NickArgyle  https://www.npmjs.com/package/@irman/nativescript-screen-orientation

**Comment by NArgyle** [comment]
Thanks for doing this. I'll be switching to your fork in my next build.

**Comment by bathejasumeet** [comment]
v2.0 works with xcode 8, webpack, NS 2.5 and iOS 10.2
